name: daily_quotes
description: "A simple package that provides motivational quotes."
version: 0.0.2
homepage: https://github.com/nadiaperestp83-eng/Daily_Quotes_update
repository: https://github.com/nadiaperestp83-eng/Daily_Quotes_update

environment:
  sdk: ">=3.0.0 <4.0.0"

topics:
  - quotes
  - motivation
  - dart

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
